# Generated by Django 5.2 on 2025-04-09 10:27

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_hotels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=32)),
                ('country_name_en', models.CharField(max_length=32, null=True)),
                ('country_name_ru', models.CharField(max_length=32, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='city_image',
            field=models.ImageField(default=1, upload_to='city_images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='city_name_en',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='city_name_ru',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='hotel_description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='hotel_description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='hotel_name_en',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='hotel_name_ru',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='hotel_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking_hotels.hotel'),
        ),
        migrations.AddField(
            model_name='review',
            name='hotel_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking_hotels.hotel'),
        ),
        migrations.AddField(
            model_name='review',
            name='text_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='text_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='user_name_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='user_name_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='room',
            name='room_description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='room_description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='country_user',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hotelimage',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels_image', to='booking_hotels.hotel'),
        ),
        migrations.AlterField(
            model_name='review',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking_hotels.hotel'),
        ),
        migrations.AlterField(
            model_name='room',
            name='hotel_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking_hotels.hotel'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AddField(
            model_name='hotel',
            name='country_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking_hotels.country'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='country_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking_hotels.country'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking_hotels.country'),
        ),
    ]
